[project]
name = "mcp-getting-started"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx[socks]>=0.28.1",
    "mcp[cli]>=1.9.0",
    "openai>=1.81.0",
    "python-dotenv>=1.1.0",
]
